name: NLP_E1282
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py312h8acbcb3_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=py312hca03da5_0
  - appnope=0.1.4=py312hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h254cc4a_0
  - asttokens=3.0.0=py312hca03da5_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=24.3.0=py312hca03da5_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h12fd690_2
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - babel=2.16.0=py312hca03da5_0
  - beautifulsoup4=4.13.5=py312hca03da5_0
  - bleach=6.2.0=py312hca03da5_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotlicffi=1.0.9.2=py312h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.12.2=hca03da5_0
  - catalogue=2.0.10=py312h81bd7bf_2
  - certifi=2025.11.12=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.0=pyh707e725_0
  - cloudpathlib=0.23.0=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py312hca03da5_0
  - confection=0.1.5=pyhecae5ae_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.11=py312h6b01ec3_1
  - cython=3.1.4=py312hd9aa7d2_2
  - cython-blis=1.3.0=py312he0011b7_0
  - datasets=4.2.0=pyhcf101f3_0
  - debugpy=1.8.16=py312h0962b89_0
  - decorator=5.2.1=py312hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=pyhd8ed1ab_0
  - executing=2.2.1=py312hca03da5_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py312h5748b74_0
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.7.0=py312h512c567_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gensim=4.3.3=py312hd77ebd4_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - h11=0.16.0=py312hca03da5_0
  - hf-xet=1.1.10=py310hdcd56a2_2
  - httpcore=1.0.9=py312hca03da5_0
  - httpx=0.28.1=py312hca03da5_0
  - huggingface_hub=0.35.3=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.7=py312hca03da5_0
  - ipykernel=6.30.1=py312hca03da5_0
  - ipython=9.5.0=py312hca03da5_0
  - ipython_pygments_lexers=1.1.1=py312hca03da5_0
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.9.25=py312hca03da5_0
  - jsonschema=4.25.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter-lsp=2.2.5=py312hca03da5_0
  - jupyter_client=8.6.3=py312hca03da5_0
  - jupyter_core=5.8.1=py312hca03da5_0
  - jupyter_events=0.12.0=py312hca03da5_0
  - jupyter_server=2.16.0=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=py312hca03da5_0
  - jupyterlab=4.4.7=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=py312hca03da5_0
  - jupyterlab_server=2.27.3=py312hca03da5_0
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=21.0.0=hd43feaf_8_cpu
  - libarrow-acero=21.0.0=hc317990_8_cpu
  - libarrow-compute=21.0.0=h75845d1_8_cpu
  - libarrow-dataset=21.0.0=hc317990_8_cpu
  - libarrow-substrait=21.0.0=h144af7f_8_cpu
  - libblas=3.9.0=36_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=36_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=hcdac78c_0
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=36_hd9741b5_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_8_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h702a38d_1
  - libre2-11=2025.08.12=h91c62da_1
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=hfce79cd_1
  - libutf8proc=2.11.0=hc25f550_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=h4a912ad_3
  - lz4-c=1.10.0=h286801f_1
  - marisa-trie=1.3.1=py312h0962b89_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.6=py312h1f38498_1
  - matplotlib-base=3.10.6=py312h605b88b_1
  - matplotlib-inline=0.1.7=py312hca03da5_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.2=py312hca03da5_0
  - multidict=6.6.3=py312hdb8e49c_0
  - multiprocess=0.70.16=py312h024a12e_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - murmurhash=1.0.13=py312he360a15_1
  - nbclient=0.10.2=py312hca03da5_0
  - nbconvert-core=7.16.6=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - nlohmann_json=3.12.0=h248ca61_1
  - nltk=3.9.2=pyhcf101f3_1
  - notebook=7.4.5=py312hca03da5_0
  - notebook-shim=0.2.4=py312hca03da5_0
  - numpy=1.26.4=py312h8442bc7_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=25.0=py312hca03da5_0
  - pandas=2.3.3=py312h5978115_1
  - pandocfilters=1.5.1=py312hca03da5_0
  - parso=0.8.4=py312hca03da5_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=py312hca03da5_0
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py312hca03da5_0
  - preshed=3.0.9=py312hf02c72a_2
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.21.1=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py312h998013c_0
  - psutil=7.0.0=py312h254cc4a_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py312hca03da5_0
  - pyarrow=21.0.0=py312h1f38498_1
  - pyarrow-core=21.0.0=py312hea229ce_1_cpu
  - pycparser=2.23=py312hca03da5_0
  - pydantic=2.12.0=pyh3cfb1c2_0
  - pydantic-core=2.41.1=py312h6ef9ec0_0
  - pygments=2.19.1=py312hca03da5_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.8=h89a136b_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=3.2.1=py312hca03da5_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h692f514_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=27.1.0=py312h854a7ef_0
  - qhull=2020.2=h420ef59_5
  - qtconsole=5.7.0=py312hca03da5_0
  - qtpy=2.4.3=py312hca03da5_0
  - re2=2025.08.12=h64b956e_1
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py312hca03da5_0
  - regex=2025.10.23=py312h4409184_0
  - requests=2.32.5=py312hca03da5_0
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.22.3=py312h2aea54e_0
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.13.1=py312h14ffa8f_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py312hca03da5_1
  - setuptools=78.1.1=py312hca03da5_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=py312hca03da5_0
  - smart-open=7.3.1=h08b120a_0
  - smart_open=7.3.1=pyhcf101f3_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - spacy=3.8.7=py312h708dc23_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlite=3.50.2=h79febb2_1
  - srsly=2.5.1=py312hd8f9ff3_1
  - stack_data=0.6.3=py312hca03da5_0
  - statsmodels=0.14.5=py312ha11c99a_1
  - terminado=0.18.1=py312hca03da5_0
  - thinc=8.3.6=py312h708dc23_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py312h80987f9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py312hca03da5_0
  - typer=0.19.2=pyhef33e25_0
  - typer-slim=0.19.2=pyhcf101f3_0
  - typer-slim-standard=0.19.2=h6e3bb38_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - ujson=5.11.0=py312he360a15_1
  - unicodedata2=16.0.0=py312h163523d_1
  - urllib3=2.5.0=py312hca03da5_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=py312hca03da5_0
  - weasel=0.4.1=pyhd8ed1ab_2
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - wrapt=1.17.3=py312h163523d_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xxhash=0.8.3=haa4e116_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.20.1=py312h998013c_0
  - youtube-transcript-api=1.2.3=pyhcf101f3_0
  - yt-dlp=2025.12.8=pyhcf101f3_2
  - yt-dlp-ejs=0.3.2=pyhcf101f3_2
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - en-core-web-sm==3.8.0
      - fasttext==0.9.3
      - pybind11==3.0.1
prefix: /opt/anaconda3/envs/NLP_E1282
